myProject/gradesApp/urls.py
from django.urls import path
from gradesApp import views

app_name='gradesApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('registerStudent/',views.registerStudent,name='registerStudent'),
    path('registerTeacher/',views.registerTeacher,name='registerTeacher'),
    path('login/',views.userLogin,name='userLogin'),
    path('dashboard',views.dashboard,name='dashboard'),
   
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from gradesApp import views

urlpatterns = [
    path('gradesApp/',include('gradesApp.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('logout/',views.userLogout,name='logout'),
    path('studentDash/',views.studentDash,name='studentDash'),
    path('teacherDash/',views.teacherDash,name='teacherDash'),
   
]

myProject/gradesApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Student(models.Model):
    student=models.OneToOneField(User,on_delete=models.CASCADE)
    idno=models.IntegerField(blank=False)
    branch=models.CharField(max_length=256,blank=False)
    is_student=models.BooleanField(default=True)

    def __str__(self):
        return self.student.username

class Teacher(models.Model):
    teacher=models.OneToOneField(User,on_delete=models.CASCADE)
    subject=models.CharField(max_length=256,blank=False)
    phone=models.IntegerField()
    is_student=models.BooleanField(default=False)

    def __str__(self):
        return self.teacher.username

myProject/gradesApp/forms.py
from django import forms
from django.contrib.auth.models import User
from gradesApp.models import Student,Teacher

class studentForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']

BRANCH_CHOICES = (
    ('COMPS','COMPS'),
    ('IT','IT'),
    ('EXTC','EXTC')
)
class studentAddForm(forms.ModelForm):
    branch=forms.CharField(widget=forms.Select(choices=BRANCH_CHOICES))
    class Meta():
        model=Student
        fields=['idno','branch']

class teacherForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']

SUBJECT_CHOICES=(
    ('DS','Data Structures'),
    ('DLD','Digital Logic Design'),
    ('DM','Discrete Mathematics'),
    ('LA','Linear Algebra')
)

class teacherAddForm(forms.ModelForm):
    subject=forms.CharField(widget=forms.Select(choices=SUBJECT_CHOICES))
    class Meta():
        model=Teacher
        fields=['subject','phone']


        

myProject/gradesApp/views.py
from django.shortcuts import render,redirect
from gradesApp.forms import studentForm,studentAddForm,teacherForm,teacherAddForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from gradesApp.models import Student,Teacher 
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    return render(request,'gradesApp/index.html')

@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    return render(request,'gradesApp/register.html')

def registerStudent(request):
    registered=False
    if request.method=='POST':
        var_studentForm=studentForm(request.POST)
        var_studentAddForm=studentAddForm(request.POST)
        if var_studentForm.is_valid() and var_studentAddForm.is_valid():
            studentprimary=var_studentForm.save()
            studentprimary.set_password(studentprimary.password)
            studentprimary.save()
            studentAdd=var_studentAddForm.save(commit=False)
            studentAdd.student=studentprimary
            studentAdd.save()
            registered=True
    else:
        var_studentForm=studentForm()
        var_studentAddForm=studentAddForm()
    return render(request,'gradesApp/registerStudent.html',{'var_studentForm':var_studentForm,'var_studentAddForm':var_studentAddForm,'registered':registered})


def registerTeacher(request):
    registered=False
    if request.method=='POST':
        var_teacherForm=teacherForm(request.POST)
        var_teacherAddForm=teacherAddForm(request.POST)
        if var_teacherForm.is_valid() and var_teacherAddForm.is_valid():
            teacherprimary=var_teacherForm.save()
            teacherprimary.set_password(teacherprimary.password)
            teacherprimary.save()
            teacherAdd=var_teacherAddForm.save(commit=False)
            teacherAdd.teacher=teacherprimary
            teacherAdd.save()
            registered=True
    else:
        var_teacherForm=teacherForm()
        var_teacherAddForm=teacherAddForm()
    return render(request,'gradesApp/registerTeacher.html',{'var_teacherForm':var_teacherForm,'var_teacherAddForm':var_teacherAddForm,'registered':registered})
    
def userLogin(request):
    invalidlogin=False
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            invalidlogin=True
            return redirect('/gradesApp/login/')
    else:
        return render(request,'gradesApp/login.html',{'invalidlogin':invalidlogin})

@login_required
def dashboard(request):
    try:
        current=Student.objects.get(student=request.user)
    except Student.DoesNotExist:
        current=Teacher.objects.get(teacher=request.user)
    if current.is_student:
        return redirect('/studentDash/')
    else:
        return redirect('/teacherDash/')
    return render(request,'gradesApp/dashboard.html')

    

def studentDash(request):
    return render(request,'gradesApp/studentDash.html')

def teacherDash(request):
    return render(request,'gradesApp/teacherDash.html')

myProject/templates/gradesApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>myGrades</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url "index" %}">Home</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
                </li>
                
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "gradesApp:register" %}">Register</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "gradesApp:dashboard" %}">Dashboard</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "logout" %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "gradesApp:userLogin" %}"
                        >Login</a
                        >
                    </li>
                {% endif %}
               
            </ul>
            
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

myProject/templates/gradesApp/dashboard.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}
{% endblock %}

myProject/templates/gradesApp/index.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1 class="display-3">My Grades</h1>
    <p class="lead">Helps to connect Students and Teachers over the internet</p>
    <hr class="my-2">
    <p>View your marks and get notes directly from teachers</p>
</div>

{% endblock %}

myProject/templates/gradesApp/login.html
{% extends "gradesApp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    {% if invalidlogin %}
        <h3>Please enter correct login details!</h3>
    {% endif %}
    <form action="{% url 'gradesApp:userLogin' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password: </label>
        <input type="password" name="password" placeholder="Enter Password">
        <input type="Submit" value="Login">
    </form>
</div>

{% endblock %}

myProject/templates/gradesApp/register.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1 class="display-3">Register Here!</h1>
   
    <hr class="my-2">
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url "gradesApp:registerStudent" %}" role="button">I'm a Student</a>
        <a class="btn btn-primary btn-lg" href="{% url "gradesApp:registerTeacher" %}" role="button">I'm a Teacher</a>
    </p>
</div>

{% endblock %}

myProject/templates/gradesApp/registerStudent.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Students:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_studentForm.as_p }}
            {{ var_studentAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

myProject/templates/gradesApp/registerTeacher.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Teachers:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_teacherForm.as_p }}
            {{ var_teacherAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

myProject/templates/gradesApp/studentDash.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Student Dash</h2>
        <hr>
    </div>
</div>


{% endblock %}

myProject/templates/gradesApp/teacherDash.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Teacher Dash</h2>
        <hr>
    </div>
</div>

{% endblock %}